### ISSUE TITLE
Placement of "Explore" not Ok

### ISSUE THREAD

**Issue by rlaemmel** [101companies/101wiki#365] opened 2014-03-11 23:24 UTC
cc @burgua 
cc @arkadi-schmidt 

I am rendering this
http://101companies.org/wiki/Hello_world_program
with latest Chrome:

![image](https://f.cloud.github.com/assets/1208815/2392198/498980f4-a974-11e3-9066-27d3ecaeffbb.png)

**Comment by rlaemmel** [comment] 2014-03-11 23:26
In fact, this is a more serious problem than I thought.
Look closely -- the source code of the program is missing altogether.
Do we need to pull in the fragment locator guys?
Also cc-ing @martinleinberger as he might understand what's going on.
BTW, I am starting a course at WHU on Thursday -- with good usage of 101 :-)

**Comment by burgua** [comment] 2014-03-12 05:44
It looks like content of files is empty on worker

**Comment by martinleinberger** [comment] 2014-03-12 08:51
I can confirm that apparently, derived resources are not produced for the concepts folder right now. If there are no .matches.json files for these resources, then the explorer doesn't know anything about these files. 
I'm not sure why... didn't Kevin change the modules so that they operate over all folders?

I'll investigate as soon as possible...

**Comment by martinleinberger** [comment] 2014-03-12 12:36
Should be fixed...

**Closed as completed by martinleinberger** 2014-03-12 12:36 UTC
Labels: bug

**Comment by burgua** [comment] 2014-03-12 12:38
Und die Seite sieht gut aus
